### ISSUE TITLE
Lacking LICENSE

### ISSUE THREAD

**Issue by mazunki** [mattmelling/mpvyt#2]
Hey, I was making an ebuild for Gentoo of this project, and got stuck at the lack of a license.

Since there is no license attached to the repository, I'm assuming GPL-3 is fine? If that's the case, I've created #1 with a copy of it. There's also some other runtime issues I want to fix.

**Comment by mattmelling** [comment]
Thanks! GPL-3 is fine. This has been a little neglected as my media consumption has waned, but happy to take PRs so don't hold back.
